import type {
  Activity,
  CEFRLevel,
  ClassData,
  ActivityMetric,
  ChartConfig,
  TopPerformer,
  AnalyticsInsight,
} from "~/types/activities";
import type { AssignedStudent } from "~/components/activities/table/AssignedStudentsTable.vue";

export const getMockActivities = (): Activity[] => [
  {
    id: "1",
    title: "Ordering Delicious Dishes at a Restaurant",
    description:
      "In this scenario, you are at a restaurant wanting to order food. I will be the waiter, and I will ask you for your order and recommend some dishes.",
    coverImage: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&h=450&fit=crop",
    level: "A2" as CEFRLevel,
    theme: "Restaurant & Food",
    learningObjective: "Ordering food at a restaurant",
    aiAssistantRole: "Waiter",
    studentRole: "Customer",
    assignedClasses: 3,
    totalStudents: 76,
    completions: 28,
    avgScore: 78,
    isFavorite: false,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-20"),
  },
  {
    id: "2",
    title: "Ordering Food with Confidence",
    description: "Practice ordering food in a casual dining setting with confidence and proper etiquette.",
    coverImage: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&h=450&fit=crop",
    level: "A2" as CEFRLevel,
    theme: "Restaurant & Food",
    learningObjective: "Building confidence in food ordering",
    aiAssistantRole: "Server",
    studentRole: "Diner",
    assignedClasses: 2,
    totalStudents: 48,
    completions: 15,
    avgScore: 82,
    isFavorite: false,
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "3",
    title: "Buying Food at the Market",
    description: "Navigate a local market, ask about prices, and purchase fresh produce.",
    coverImage: "https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=800&h=450&fit=crop",
    level: "B1" as CEFRLevel,
    theme: "Shopping",
    learningObjective: "Market shopping vocabulary and negotiation",
    aiAssistantRole: "Vendor",
    studentRole: "Shopper",
    assignedClasses: 5,
    totalStudents: 124,
    completions: 67,
    avgScore: 85,
    isFavorite: true,
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-01-22"),
  },
  {
    id: "4",
    title: "Discussing Project Plans",
    description: "Collaborate with team members to discuss and plan a business project.",
    coverImage: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=800&h=450&fit=crop",
    level: "B2" as CEFRLevel,
    theme: "Business",
    learningObjective: "Professional communication and planning",
    aiAssistantRole: "Team Lead",
    studentRole: "Team Member",
    assignedClasses: 1,
    totalStudents: 32,
    completions: 18,
    avgScore: 88,
    isFavorite: false,
    createdAt: new Date("2024-01-12"),
    updatedAt: new Date("2024-01-19"),
  },
  {
    id: "5",
    title: "Practicing Job Interviews",
    description: "Prepare for job interviews with common questions and professional responses.",
    coverImage: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=800&h=450&fit=crop",
    level: "B2" as CEFRLevel,
    theme: "Career",
    learningObjective: "Interview skills and professional vocabulary",
    aiAssistantRole: "Interviewer",
    studentRole: "Candidate",
    assignedClasses: 4,
    totalStudents: 89,
    completions: 42,
    avgScore: 79,
    isFavorite: false,
    createdAt: new Date("2024-01-08"),
    updatedAt: new Date("2024-01-21"),
  },
  {
    id: "6",
    title: "Collaborating on Team Projects",
    description: "Work together with colleagues on a collaborative team project.",
    coverImage: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&h=450&fit=crop",
    level: "B1" as CEFRLevel,
    theme: "Business",
    learningObjective: "Teamwork and collaboration vocabulary",
    aiAssistantRole: "Colleague",
    studentRole: "Team Member",
    assignedClasses: 3,
    totalStudents: 72,
    completions: 38,
    avgScore: 81,
    isFavorite: false,
    createdAt: new Date("2024-01-14"),
    updatedAt: new Date("2024-01-20"),
  },
  {
    id: "7",
    title: "Mock Interview Practice",
    description: "Realistic job interview simulation with feedback and improvement tips.",
    coverImage: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=800&h=450&fit=crop",
    level: "C1" as CEFRLevel,
    theme: "Career",
    learningObjective: "Advanced interview techniques",
    aiAssistantRole: "HR Manager",
    studentRole: "Job Applicant",
    assignedClasses: 2,
    totalStudents: 45,
    completions: 23,
    avgScore: 92,
    isFavorite: false,
    createdAt: new Date("2024-01-11"),
    updatedAt: new Date("2024-01-19"),
  },
  {
    id: "8",
    title: "Asking for Directions",
    description: "Learn to ask for and give directions in various urban settings.",
    coverImage: "https://images.unsplash.com/photo-1524661135-423995f22d0b?w=800&h=450&fit=crop",
    level: "A2" as CEFRLevel,
    theme: "Travel",
    learningObjective: "Navigation and direction vocabulary",
    aiAssistantRole: "Local Resident",
    studentRole: "Tourist",
    assignedClasses: 6,
    totalStudents: 156,
    completions: 89,
    avgScore: 76,
    isFavorite: false,
    createdAt: new Date("2024-01-09"),
    updatedAt: new Date("2024-01-21"),
  },
];

export const getMockClasses = (): ClassData[] => [
  {
    id: "1",
    name: "English A2 - Morning Group",
    country: "Spain",
    flag: "flag:us-4x3",
    level: "A2" as CEFRLevel,
    studentCount: 25,
  },
  {
    id: "2",
    name: "English B1 - Intermediate",
    country: "France",
    flag: "flag:fr-4x3",
    level: "B1" as CEFRLevel,
    studentCount: 28,
  },
  {
    id: "3",
    name: "English A2 - Evening Class",
    country: "Italy",
    flag: "flag:it-4x3",
    level: "A2" as CEFRLevel,
    studentCount: 23,
  },
  {
    id: "4",
    name: "English B2 - Advanced",
    country: "Germany",
    flag: "flag:de-4x3",
    level: "B2" as CEFRLevel,
    studentCount: 32,
  },
  {
    id: "5",
    name: "English C1 - Professional",
    country: "Netherlands",
    flag: "flag:nl-4x3",
    level: "C1" as CEFRLevel,
    studentCount: 18,
  },
  {
    id: "6",
    name: "English B1 - Business English",
    country: "Portugal",
    flag: "flag:pt-4x3",
    level: "B1" as CEFRLevel,
    studentCount: 30,
  },
];

export const generateId = (): string => {
  return `${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
};

// Mock data for activity detail page
export const getMockAssignedStudents = (_activityId: string): AssignedStudent[] => [
  {
    id: "1",
    name: "Emma Wilson",
    avatarUrl: "https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=120",
    className: "Business English Advanced",
    status: "completed",
    score: 92,
  },
  {
    id: "2",
    name: "James Chen",
    avatarUrl: "https://images.pexels.com/photos/2379005/pexels-photo-2379005.jpeg?auto=compress&cs=tinysrgb&w=120",
    className: "Business English Advanced",
    status: "completed",
    score: 88,
  },
  {
    id: "3",
    name: "Sofia Rodriguez",
    avatarUrl: "https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=120",
    className: "Business English Advanced",
    status: "pending",
    score: null,
  },
  {
    id: "4",
    name: "Lucas Smith",
    avatarUrl: "https://images.pexels.com/photos/3760852/pexels-photo-3760852.jpeg?auto=compress&cs=tinysrgb&w=120",
    className: "Conversational English",
    status: "completed",
    score: 95,
  },
  {
    id: "5",
    name: "Mia Johnson",
    className: "Conversational English",
    status: "pending",
    score: null,
  },
  {
    id: "6",
    name: "Oliver Brown",
    avatarUrl: "https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=120",
    className: "English for Beginners",
    status: "completed",
    score: 78,
  },
  {
    id: "7",
    name: "Ava Martinez",
    avatarUrl: "https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=120",
    className: "English for Beginners",
    status: "pending",
    score: null,
  },
  {
    id: "8",
    name: "Noah Davis",
    className: "English for Beginners",
    status: "pending",
    score: null,
  },
];

export const getMockActivityMetrics = (_activityId: string): ActivityMetric[] => [
  {
    id: "shares",
    label: "Community Shares",
    value: "28",
    icon: "solar:share-line-duotone",
    color: "info",
    trend: "+12%",
  },
  {
    id: "favorites",
    label: "Marked as Favorite",
    value: "142",
    icon: "solar:star-bold-duotone",
    color: "warning",
    trend: "+8%",
  },
  {
    id: "completions",
    label: "Total Completions",
    value: "4",
    icon: "lucide:check",
    color: "success",
    trend: "+24%",
  },
  {
    id: "avgScore",
    label: "Average Score",
    value: "88%",
    icon: "solar:medal-ribbon-line-duotone",
    color: "primary",
    trend: "+5%",
  },
];

export const getMockWeeklyProgressChart = (_activityId: string): ChartConfig => ({
  data: {
    labels: ["Week 1", "Week 2", "Week 3", "Week 4"],
    datasets: [
      {
        label: "Average Score",
        data: [62, 70, 76, 84],
        borderColor: "#3B82F6",
        backgroundColor: "rgba(59,130,246,0.12)",
        tension: 0.4,
        fill: true,
        pointRadius: 4,
        pointBackgroundColor: "#3B82F6",
      },
    ],
  },
  options: {
    maintainAspectRatio: false,
    responsive: true,
    plugins: {
      legend: { display: false },
      tooltip: {
        enabled: true,
        callbacks: {},
      },
    },
    scales: {
      x: {
        grid: {
          display: false,
          drawBorder: false,
        },
        ticks: {
          color: "#94A3B8",
          font: { size: 11 },
        },
      },
      y: {
        grid: {
          color: "#E2E8F0",
          drawBorder: false,
        },
        ticks: {
          stepSize: 25,
          color: "#94A3B8",
          font: { size: 11 },
        },
      },
    },
  },
});

export const getMockScoreDistributionChart = (_activityId: string): ChartConfig => ({
  data: {
    labels: ["0–50", "51–70", "71–85", "86–100"],
    datasets: [
      {
        data: [0.5, 1, 1, 2],
        backgroundColor: "#10B981",
      },
    ],
  },
  options: {
    maintainAspectRatio: false,
    responsive: true,
    plugins: {
      legend: { display: false },
    },
    scales: {
      x: {
        grid: {
          display: false,
          drawBorder: false,
        },
        ticks: {
          color: "#94A3B8",
          font: { size: 11 },
        },
      },
      y: {
        grid: {
          color: "#E2E8F0",
          drawBorder: false,
        },
        ticks: {
          stepSize: 1,
          color: "#94A3B8",
          font: { size: 11 },
        },
      },
    },
  },
});

export const getMockTopPerformers = (_activityId: string): TopPerformer[] => [
  {
    id: "lucas",
    name: "Lucas Smith",
    className: "Conversational English",
    score: 95,
    rank: 1,
    color: "from-amber-400 to-amber-300",
    emoji: "👨",
  },
  {
    id: "emma",
    name: "Emma Wilson",
    className: "Business English Advanced",
    score: 92,
    rank: 2,
    color: "from-blue-400 to-blue-300",
    emoji: "👩",
  },
  {
    id: "james",
    name: "James Chen",
    className: "Business English Advanced",
    score: 88,
    rank: 3,
    color: "from-violet-400 to-violet-300",
    emoji: "👨",
  },
];

export const getMockAnalyticsInsights = (_activityId: string): AnalyticsInsight[] => [
  {
    id: "avgTime",
    icon: "lucide:clock",
    label: "Avg. Completion Time",
    value: "12 minutes",
  },
  {
    id: "completionRate",
    icon: "lucide:bar-chart-3",
    label: "Completion Rate",
    value: "50%",
  },
  {
    id: "classesEngaged",
    icon: "lucide:users",
    label: "Classes Engaged",
    value: "3 of 3",
  },
];
