#!/usr/bin/env tsx
/**
 * Generate TypeScript types from English translation files
 * This script reads the EN locale (base) and generates type definitions
 * for all translation keys to enable type-safe i18n usage
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Use institutional app as source of truth for types (both apps should have same structure)
const INSTITUTIONAL_LOCALES_DIR = path.join(__dirname, "../../../apps/institutional/src/locales");
const STUDENT_TEACHER_LOCALES_DIR = path.join(__dirname, "../../../apps/student-teacher/locales");
const OUTPUT_FILE = path.join(__dirname, "../src/types.generated.ts");

interface TranslationObject {
  [key: string]: string | TranslationObject;
}

function flattenKeys(obj: TranslationObject, prefix = ""): string[] {
  const keys: string[] = [];

  for (const [key, value] of Object.entries(obj)) {
    const fullKey = prefix ? `${prefix}.${key}` : key;

    if (typeof value === "string") {
      keys.push(fullKey);
    } else if (typeof value === "object" && value !== null) {
      keys.push(...flattenKeys(value, fullKey));
    }
  }

  return keys;
}

async function loadTranslations(): Promise<TranslationObject> {
  // Try institutional app first, fallback to student-teacher
  let enPath = path.join(INSTITUTIONAL_LOCALES_DIR, "en.ts");

  if (!fs.existsSync(enPath)) {
    enPath = path.join(STUDENT_TEACHER_LOCALES_DIR, "en.ts");
  }

  if (!fs.existsSync(enPath)) {
    throw new Error("English translation file not found in either app");
  }

  // Dynamic import of the EN locale (convert to file URL for Windows compatibility)
  const fileUrl = pathToFileURL(enPath).href;
  const module = await import(fileUrl);
  return module.default;
}

function generateTypes(translations: TranslationObject): string {
  const keys = flattenKeys(translations);

  const typeDefinition = `/**
 * Auto-generated translation keys
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-types.ts
 * Run: pnpm i18n:types to regenerate
 */

export type TranslationKey =
${keys.map((key) => `  | '${key}'`).join("\n")};

export const TRANSLATION_KEYS = [
${keys.map((key) => `  '${key}',`).join("\n")}
] as const;

export type TranslationKeyCount = ${keys.length};
`;

  return typeDefinition;
}

async function main() {
  try {
    console.log("🔍 Loading English translations...");
    const translations = await loadTranslations();

    console.log("📝 Generating TypeScript types...");
    const typeContent = generateTypes(translations);

    console.log("💾 Writing types to file...");
    fs.writeFileSync(OUTPUT_FILE, typeContent, "utf-8");

    const keyCount = flattenKeys(translations).length;
    console.log(`✅ Successfully generated types for ${keyCount} translation keys`);
    console.log(`📄 Output: ${OUTPUT_FILE}`);
  } catch (error) {
    console.error("❌ Error generating types:", error);
    process.exit(1);
  }
}

main();
