import { ref } from "vue";
import type { Student } from "~/composables/students/types";
import { loadClassesFromStorage, saveClassesToStorage } from "./useClasses";

/**
 * Mock data generator for students by class
 * Each class has different students with varying progress
 */
export function getMockClassStudents(classId: string): Student[] {
  const now = new Date();
  const oneMonthAgo = new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000);
  const twoWeeksAgo = new Date(now.getTime() - 14 * 24 * 60 * 60 * 1000);
  const oneWeekAgo = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);

  // Class 1: Business English Advanced - 12 students, high progress
  if (classId === "1") {
    return [
      {
        id: "s1",
        firstName: "Michael",
        lastName: "Chen",
        email: "michael.chen@example.com",
        photo: "https://i.pravatar.cc/150?img=11",
        level: "C1",
        progress: 92,
        activitiesCompleted: 18,
        activitiesTotal: 20,
        studyTimeMinutes: 450,
        score: 94,
        enrolledAt: oneMonthAgo.toISOString(),
        skills: {
          pronunciation: 90,
          vocabulary: 95,
          grammar: 93,
          fluency: 91,
        },
      },
      {
        id: "s2",
        firstName: "Emma",
        lastName: "Rodriguez",
        email: "emma.rodriguez@example.com",
        photo: "https://i.pravatar.cc/150?img=12",
        level: "C1",
        progress: 88,
        activitiesCompleted: 17,
        activitiesTotal: 20,
        studyTimeMinutes: 420,
        score: 91,
        enrolledAt: oneMonthAgo.toISOString(),
        skills: {
          pronunciation: 88,
          vocabulary: 92,
          grammar: 90,
          fluency: 89,
        },
      },
      {
        id: "s3",
        firstName: "James",
        lastName: "Wilson",
        email: "james.wilson@example.com",
        photo: "https://i.pravatar.cc/150?img=13",
        level: "C1",
        progress: 85,
        activitiesCompleted: 16,
        activitiesTotal: 20,
        studyTimeMinutes: 380,
        score: 88,
        enrolledAt: oneMonthAgo.toISOString(),
        skills: {
          pronunciation: 85,
          vocabulary: 89,
          grammar: 87,
          fluency: 86,
        },
      },
      {
        id: "s4",
        firstName: "Sophia",
        lastName: "Martinez",
        email: "sophia.martinez@example.com",
        photo: "https://i.pravatar.cc/150?img=14",
        level: "C1",
        progress: 90,
        activitiesCompleted: 18,
        activitiesTotal: 20,
        studyTimeMinutes: 440,
        score: 93,
        enrolledAt: oneMonthAgo.toISOString(),
        skills: {
          pronunciation: 91,
          vocabulary: 94,
          grammar: 92,
          fluency: 90,
        },
      },
      {
        id: "s5",
        firstName: "David",
        lastName: "Anderson",
        email: "david.anderson@example.com",
        photo: "https://i.pravatar.cc/150?img=15",
        level: "C1",
        progress: 82,
        activitiesCompleted: 15,
        activitiesTotal: 20,
        studyTimeMinutes: 350,
        score: 85,
        enrolledAt: oneMonthAgo.toISOString(),
        skills: {
          pronunciation: 80,
          vocabulary: 86,
          grammar: 84,
          fluency: 83,
        },
      },
      {
        id: "s6",
        firstName: "Olivia",
        lastName: "Taylor",
        email: "olivia.taylor@example.com",
        photo: "https://i.pravatar.cc/150?img=16",
        level: "C1",
        progress: 79,
        activitiesCompleted: 14,
        activitiesTotal: 20,
        studyTimeMinutes: 320,
        score: 82,
        enrolledAt: twoWeeksAgo.toISOString(),
        skills: {
          pronunciation: 77,
          vocabulary: 83,
          grammar: 81,
          fluency: 80,
        },
      },
      {
        id: "s7",
        firstName: "William",
        lastName: "Brown",
        email: "william.brown@example.com",
        photo: "https://i.pravatar.cc/150?img=17",
        level: "C1",
        progress: 91,
        activitiesCompleted: 18,
        activitiesTotal: 20,
        studyTimeMinutes: 460,
        score: 95,
        enrolledAt: oneMonthAgo.toISOString(),
        skills: {
          pronunciation: 92,
          vocabulary: 96,
          grammar: 94,
          fluency: 93,
        },
      },
      {
        id: "s8",
        firstName: "Isabella",
        lastName: "Garcia",
        email: "isabella.garcia@example.com",
        photo: "https://i.pravatar.cc/150?img=18",
        level: "C1",
        progress: 86,
        activitiesCompleted: 16,
        activitiesTotal: 20,
        studyTimeMinutes: 400,
        score: 89,
        enrolledAt: oneMonthAgo.toISOString(),
        skills: {
          pronunciation: 84,
          vocabulary: 90,
          grammar: 88,
          fluency: 87,
        },
      },
      {
        id: "s9",
        firstName: "Alexander",
        lastName: "Lee",
        email: "alexander.lee@example.com",
        photo: "https://i.pravatar.cc/150?img=19",
        level: "C1",
        progress: 84,
        activitiesCompleted: 15,
        activitiesTotal: 20,
        studyTimeMinutes: 370,
        score: 87,
        enrolledAt: twoWeeksAgo.toISOString(),
        skills: {
          pronunciation: 82,
          vocabulary: 88,
          grammar: 86,
          fluency: 85,
        },
      },
      {
        id: "s10",
        firstName: "Mia",
        lastName: "Johnson",
        email: "mia.johnson@example.com",
        photo: "https://i.pravatar.cc/150?img=20",
        level: "C1",
        progress: 88,
        activitiesCompleted: 17,
        activitiesTotal: 20,
        studyTimeMinutes: 430,
        score: 92,
        enrolledAt: oneMonthAgo.toISOString(),
        skills: {
          pronunciation: 86,
          vocabulary: 93,
          grammar: 91,
          fluency: 90,
        },
      },
      {
        id: "s11",
        firstName: "Benjamin",
        lastName: "Davis",
        email: "benjamin.davis@example.com",
        photo: "https://i.pravatar.cc/150?img=21",
        level: "C1",
        progress: 81,
        activitiesCompleted: 14,
        activitiesTotal: 20,
        studyTimeMinutes: 340,
        score: 84,
        enrolledAt: twoWeeksAgo.toISOString(),
        skills: {
          pronunciation: 79,
          vocabulary: 85,
          grammar: 83,
          fluency: 82,
        },
      },
      {
        id: "s12",
        firstName: "Charlotte",
        lastName: "Miller",
        email: "charlotte.miller@example.com",
        photo: "https://i.pravatar.cc/150?img=22",
        level: "C1",
        progress: 83,
        activitiesCompleted: 15,
        activitiesTotal: 20,
        studyTimeMinutes: 360,
        score: 86,
        enrolledAt: oneMonthAgo.toISOString(),
        skills: {
          pronunciation: 81,
          vocabulary: 87,
          grammar: 85,
          fluency: 84,
        },
      },
    ];
  }

  // Class 2: Conversational Spanish - 8 students, medium progress
  if (classId === "2") {
    return [
      {
        id: "s13",
        firstName: "Carlos",
        lastName: "Mendoza",
        email: "cmendoza@gmail.com",
        photo: "https://i.pravatar.cc/150?img=5",
        level: "B1",
        progress: 72,
        activitiesCompleted: 14,
        activitiesTotal: 20,
        studyTimeMinutes: 280,
        score: 78,
        enrolledAt: twoWeeksAgo.toISOString(),
        skills: {
          pronunciation: 70,
          vocabulary: 75,
          grammar: 73,
          fluency: 71,
        },
      },
      {
        id: "s14",
        firstName: "Ana",
        lastName: "García",
        email: "anagarcia@gmail.com",
        photo: "https://i.pravatar.cc/150?img=6",
        level: "B1",
        progress: 68,
        activitiesCompleted: 13,
        activitiesTotal: 20,
        studyTimeMinutes: 250,
        score: 74,
        enrolledAt: twoWeeksAgo.toISOString(),
        skills: {
          pronunciation: 66,
          vocabulary: 72,
          grammar: 70,
          fluency: 69,
        },
      },
      {
        id: "s15",
        firstName: "Luis",
        lastName: "Fernandez",
        email: "luis.fernandez@example.com",
        photo: "https://i.pravatar.cc/150?img=23",
        level: "B1",
        progress: 65,
        activitiesCompleted: 12,
        activitiesTotal: 20,
        studyTimeMinutes: 220,
        score: 71,
        enrolledAt: twoWeeksAgo.toISOString(),
        skills: {
          pronunciation: 63,
          vocabulary: 69,
          grammar: 67,
          fluency: 66,
        },
      },
      {
        id: "s16",
        firstName: "Maria",
        lastName: "Lopez",
        email: "maria.lopez@example.com",
        photo: "https://i.pravatar.cc/150?img=24",
        level: "B1",
        progress: 75,
        activitiesCompleted: 15,
        activitiesTotal: 20,
        studyTimeMinutes: 300,
        score: 81,
        enrolledAt: twoWeeksAgo.toISOString(),
        skills: {
          pronunciation: 73,
          vocabulary: 78,
          grammar: 76,
          fluency: 74,
        },
      },
      {
        id: "s17",
        firstName: "Juan",
        lastName: "Perez",
        email: "juan.perez@example.com",
        photo: "https://i.pravatar.cc/150?img=25",
        level: "B1",
        progress: 58,
        activitiesCompleted: 11,
        activitiesTotal: 20,
        studyTimeMinutes: 180,
        score: 65,
        enrolledAt: oneWeekAgo.toISOString(),
        skills: {
          pronunciation: 56,
          vocabulary: 62,
          grammar: 60,
          fluency: 59,
        },
      },
      {
        id: "s18",
        firstName: "Carmen",
        lastName: "Sanchez",
        email: "carmen.sanchez@example.com",
        photo: "https://i.pravatar.cc/150?img=26",
        level: "B1",
        progress: 70,
        activitiesCompleted: 13,
        activitiesTotal: 20,
        studyTimeMinutes: 260,
        score: 76,
        enrolledAt: twoWeeksAgo.toISOString(),
        skills: {
          pronunciation: 68,
          vocabulary: 74,
          grammar: 72,
          fluency: 71,
        },
      },
      {
        id: "s19",
        firstName: "Pedro",
        lastName: "Gomez",
        email: "pedro.gomez@example.com",
        photo: "https://i.pravatar.cc/150?img=27",
        level: "B1",
        progress: 62,
        activitiesCompleted: 12,
        activitiesTotal: 20,
        studyTimeMinutes: 200,
        score: 68,
        enrolledAt: oneWeekAgo.toISOString(),
        skills: {
          pronunciation: 60,
          vocabulary: 66,
          grammar: 64,
          fluency: 63,
        },
      },
      {
        id: "s20",
        firstName: "Laura",
        lastName: "Torres",
        email: "laura.torres@example.com",
        photo: "https://i.pravatar.cc/150?img=28",
        level: "B1",
        progress: 55,
        activitiesCompleted: 10,
        activitiesTotal: 20,
        studyTimeMinutes: 160,
        score: 62,
        enrolledAt: oneWeekAgo.toISOString(),
        skills: {
          pronunciation: 53,
          vocabulary: 59,
          grammar: 57,
          fluency: 56,
        },
      },
    ];
  }

  // Class 3: French for Beginners - 15 students, low to medium progress
  if (classId === "3") {
    return [
      {
        id: "s21",
        firstName: "Susana",
        lastName: "Casas",
        email: "susanacasas16@gmail.com",
        photo: "https://i.pravatar.cc/150?img=1",
        level: "A2",
        progress: 48,
        activitiesCompleted: 9,
        activitiesTotal: 20,
        studyTimeMinutes: 150,
        score: 55,
        enrolledAt: oneMonthAgo.toISOString(),
        skills: {
          pronunciation: 46,
          vocabulary: 52,
          grammar: 50,
          fluency: 49,
        },
      },
      {
        id: "s22",
        firstName: "Student",
        lastName: "LingoQuesto",
        email: "student@lingoquest.com",
        photo: "https://i.pravatar.cc/150?img=2",
        level: "A2",
        progress: 52,
        activitiesCompleted: 10,
        activitiesTotal: 20,
        studyTimeMinutes: 180,
        score: 60,
        enrolledAt: oneMonthAgo.toISOString(),
        skills: {
          pronunciation: 50,
          vocabulary: 56,
          grammar: 54,
          fluency: 53,
        },
      },
      {
        id: "s23",
        firstName: "David",
        lastName: "Garzon",
        email: "david010@gmail.com",
        photo: "https://i.pravatar.cc/150?img=3",
        level: "A2",
        progress: 38,
        activitiesCompleted: 7,
        activitiesTotal: 20,
        studyTimeMinutes: 120,
        score: 48,
        enrolledAt: oneMonthAgo.toISOString(),
        skills: {
          pronunciation: 36,
          vocabulary: 42,
          grammar: 40,
          fluency: 39,
        },
      },
      {
        id: "s24",
        firstName: "Valentina",
        lastName: "Castro",
        email: "angievalentina14@gmail.com",
        photo: "https://i.pravatar.cc/150?img=4",
        level: "A2",
        progress: 45,
        activitiesCompleted: 8,
        activitiesTotal: 20,
        studyTimeMinutes: 140,
        score: 52,
        enrolledAt: oneMonthAgo.toISOString(),
        skills: {
          pronunciation: 43,
          vocabulary: 49,
          grammar: 47,
          fluency: 46,
        },
      },
      {
        id: "s25",
        firstName: "Pierre",
        lastName: "Dubois",
        email: "pierre.dubois@example.com",
        photo: "https://i.pravatar.cc/150?img=29",
        level: "A2",
        progress: 35,
        activitiesCompleted: 6,
        activitiesTotal: 20,
        studyTimeMinutes: 100,
        score: 42,
        enrolledAt: twoWeeksAgo.toISOString(),
        skills: {
          pronunciation: 33,
          vocabulary: 39,
          grammar: 37,
          fluency: 36,
        },
      },
      {
        id: "s26",
        firstName: "Marie",
        lastName: "Lefebvre",
        email: "marie.lefebvre@example.com",
        photo: "https://i.pravatar.cc/150?img=30",
        level: "A2",
        progress: 42,
        activitiesCompleted: 8,
        activitiesTotal: 20,
        studyTimeMinutes: 130,
        score: 50,
        enrolledAt: oneMonthAgo.toISOString(),
        skills: {
          pronunciation: 40,
          vocabulary: 46,
          grammar: 44,
          fluency: 43,
        },
      },
      {
        id: "s27",
        firstName: "Jean",
        lastName: "Martin",
        email: "jean.martin@example.com",
        photo: "https://i.pravatar.cc/150?img=31",
        level: "A2",
        progress: 40,
        activitiesCompleted: 7,
        activitiesTotal: 20,
        studyTimeMinutes: 125,
        score: 47,
        enrolledAt: twoWeeksAgo.toISOString(),
        skills: {
          pronunciation: 38,
          vocabulary: 44,
          grammar: 42,
          fluency: 41,
        },
      },
      {
        id: "s28",
        firstName: "Sophie",
        lastName: "Bernard",
        email: "sophie.bernard@example.com",
        photo: "https://i.pravatar.cc/150?img=32",
        level: "A2",
        progress: 30,
        activitiesCompleted: 5,
        activitiesTotal: 20,
        studyTimeMinutes: 80,
        score: 38,
        enrolledAt: oneWeekAgo.toISOString(),
        skills: {
          pronunciation: 28,
          vocabulary: 34,
          grammar: 32,
          fluency: 31,
        },
      },
      {
        id: "s29",
        firstName: "Thomas",
        lastName: "Petit",
        email: "thomas.petit@example.com",
        photo: "https://i.pravatar.cc/150?img=33",
        level: "A2",
        progress: 33,
        activitiesCompleted: 6,
        activitiesTotal: 20,
        studyTimeMinutes: 95,
        score: 40,
        enrolledAt: oneWeekAgo.toISOString(),
        skills: {
          pronunciation: 31,
          vocabulary: 37,
          grammar: 35,
          fluency: 34,
        },
      },
      {
        id: "s30",
        firstName: "Camille",
        lastName: "Roux",
        email: "camille.roux@example.com",
        photo: "https://i.pravatar.cc/150?img=34",
        level: "A2",
        progress: 50,
        activitiesCompleted: 10,
        activitiesTotal: 20,
        studyTimeMinutes: 200,
        score: 58,
        enrolledAt: oneMonthAgo.toISOString(),
        skills: {
          pronunciation: 48,
          vocabulary: 54,
          grammar: 52,
          fluency: 51,
        },
      },
      {
        id: "s31",
        firstName: "Antoine",
        lastName: "Moreau",
        email: "antoine.moreau@example.com",
        photo: "https://i.pravatar.cc/150?img=35",
        level: "A2",
        progress: 28,
        activitiesCompleted: 5,
        activitiesTotal: 20,
        studyTimeMinutes: 70,
        score: 35,
        enrolledAt: oneWeekAgo.toISOString(),
        skills: {
          pronunciation: 26,
          vocabulary: 32,
          grammar: 30,
          fluency: 29,
        },
      },
      {
        id: "s32",
        firstName: "Julie",
        lastName: "Girard",
        email: "julie.girard@example.com",
        photo: "https://i.pravatar.cc/150?img=36",
        level: "A2",
        progress: 36,
        activitiesCompleted: 6,
        activitiesTotal: 20,
        studyTimeMinutes: 110,
        score: 43,
        enrolledAt: twoWeeksAgo.toISOString(),
        skills: {
          pronunciation: 34,
          vocabulary: 40,
          grammar: 38,
          fluency: 37,
        },
      },
      {
        id: "s33",
        firstName: "Nicolas",
        lastName: "Bonnet",
        email: "nicolas.bonnet@example.com",
        photo: "https://i.pravatar.cc/150?img=37",
        level: "A2",
        progress: 32,
        activitiesCompleted: 6,
        activitiesTotal: 20,
        studyTimeMinutes: 90,
        score: 39,
        enrolledAt: oneWeekAgo.toISOString(),
        skills: {
          pronunciation: 30,
          vocabulary: 36,
          grammar: 34,
          fluency: 33,
        },
      },
      {
        id: "s34",
        firstName: "Elise",
        lastName: "Dupont",
        email: "elise.dupont@example.com",
        photo: "https://i.pravatar.cc/150?img=38",
        level: "A2",
        progress: 44,
        activitiesCompleted: 8,
        activitiesTotal: 20,
        studyTimeMinutes: 145,
        score: 51,
        enrolledAt: oneMonthAgo.toISOString(),
        skills: {
          pronunciation: 42,
          vocabulary: 48,
          grammar: 46,
          fluency: 45,
        },
      },
      {
        id: "s35",
        firstName: "Lucas",
        lastName: "Lambert",
        email: "lucas.lambert@example.com",
        photo: "https://i.pravatar.cc/150?img=39",
        level: "A2",
        progress: 25,
        activitiesCompleted: 4,
        activitiesTotal: 20,
        studyTimeMinutes: 60,
        score: 32,
        enrolledAt: oneWeekAgo.toISOString(),
        skills: {
          pronunciation: 23,
          vocabulary: 29,
          grammar: 27,
          fluency: 26,
        },
      },
    ];
  }

  // Class 4: German Grammar Intensive - 6 students, very high progress
  if (classId === "4") {
    return [
      {
        id: "s36",
        firstName: "Hans",
        lastName: "Mueller",
        email: "hans.mueller@example.com",
        photo: "https://i.pravatar.cc/150?img=40",
        level: "B2",
        progress: 98,
        activitiesCompleted: 19,
        activitiesTotal: 20,
        studyTimeMinutes: 500,
        score: 97,
        enrolledAt: oneMonthAgo.toISOString(),
        skills: {
          pronunciation: 96,
          vocabulary: 99,
          grammar: 98,
          fluency: 97,
        },
      },
      {
        id: "s37",
        firstName: "Anna",
        lastName: "Schmidt",
        email: "anna.schmidt@example.com",
        photo: "https://i.pravatar.cc/150?img=41",
        level: "B2",
        progress: 95,
        activitiesCompleted: 18,
        activitiesTotal: 20,
        studyTimeMinutes: 480,
        score: 96,
        enrolledAt: oneMonthAgo.toISOString(),
        skills: {
          pronunciation: 94,
          vocabulary: 97,
          grammar: 96,
          fluency: 95,
        },
      },
      {
        id: "s38",
        firstName: "Klaus",
        lastName: "Fischer",
        email: "klaus.fischer@example.com",
        photo: "https://i.pravatar.cc/150?img=42",
        level: "B2",
        progress: 93,
        activitiesCompleted: 18,
        activitiesTotal: 20,
        studyTimeMinutes: 460,
        score: 94,
        enrolledAt: oneMonthAgo.toISOString(),
        skills: {
          pronunciation: 91,
          vocabulary: 95,
          grammar: 94,
          fluency: 92,
        },
      },
      {
        id: "s39",
        firstName: "Greta",
        lastName: "Weber",
        email: "greta.weber@example.com",
        photo: "https://i.pravatar.cc/150?img=43",
        level: "B2",
        progress: 96,
        activitiesCompleted: 19,
        activitiesTotal: 20,
        studyTimeMinutes: 490,
        score: 98,
        enrolledAt: oneMonthAgo.toISOString(),
        skills: {
          pronunciation: 95,
          vocabulary: 98,
          grammar: 97,
          fluency: 96,
        },
      },
      {
        id: "s40",
        firstName: "Max",
        lastName: "Becker",
        email: "max.becker@example.com",
        photo: "https://i.pravatar.cc/150?img=44",
        level: "B2",
        progress: 92,
        activitiesCompleted: 17,
        activitiesTotal: 20,
        studyTimeMinutes: 440,
        score: 93,
        enrolledAt: oneMonthAgo.toISOString(),
        skills: {
          pronunciation: 90,
          vocabulary: 94,
          grammar: 93,
          fluency: 91,
        },
      },
      {
        id: "s41",
        firstName: "Lena",
        lastName: "Wagner",
        email: "lena.wagner@example.com",
        photo: "https://i.pravatar.cc/150?img=45",
        level: "B2",
        progress: 94,
        activitiesCompleted: 18,
        activitiesTotal: 20,
        studyTimeMinutes: 470,
        score: 95,
        enrolledAt: oneMonthAgo.toISOString(),
        skills: {
          pronunciation: 92,
          vocabulary: 96,
          grammar: 95,
          fluency: 94,
        },
      },
    ];
  }

  // Class 5: Italian Culture & Language - 20 students, low progress (beginners)
  if (classId === "5") {
    return [
      {
        id: "s42",
        firstName: "Marco",
        lastName: "Rossi",
        email: "marco.rossi@example.com",
        photo: "https://i.pravatar.cc/150?img=46",
        level: "A1",
        progress: 32,
        activitiesCompleted: 6,
        activitiesTotal: 20,
        studyTimeMinutes: 90,
        score: 38,
        enrolledAt: twoWeeksAgo.toISOString(),
        skills: {
          pronunciation: 30,
          vocabulary: 36,
          grammar: 34,
          fluency: 33,
        },
      },
      {
        id: "s43",
        firstName: "Giulia",
        lastName: "Bianchi",
        email: "giulia.bianchi@example.com",
        photo: "https://i.pravatar.cc/150?img=47",
        level: "A1",
        progress: 28,
        activitiesCompleted: 5,
        activitiesTotal: 20,
        studyTimeMinutes: 75,
        score: 34,
        enrolledAt: twoWeeksAgo.toISOString(),
        skills: {
          pronunciation: 26,
          vocabulary: 32,
          grammar: 30,
          fluency: 29,
        },
      },
      {
        id: "s44",
        firstName: "Alessandro",
        lastName: "Ferrari",
        email: "alessandro.ferrari@example.com",
        photo: "https://i.pravatar.cc/150?img=48",
        level: "A1",
        progress: 25,
        activitiesCompleted: 4,
        activitiesTotal: 20,
        studyTimeMinutes: 60,
        score: 30,
        enrolledAt: oneWeekAgo.toISOString(),
        skills: {
          pronunciation: 23,
          vocabulary: 29,
          grammar: 27,
          fluency: 26,
        },
      },
      // Add more students to reach 20...
      {
        id: "s45",
        firstName: "Francesca",
        lastName: "Romano",
        email: "francesca.romano@example.com",
        photo: "https://i.pravatar.cc/150?img=49",
        level: "A1",
        progress: 30,
        activitiesCompleted: 5,
        activitiesTotal: 20,
        studyTimeMinutes: 85,
        score: 36,
        enrolledAt: twoWeeksAgo.toISOString(),
        skills: {
          pronunciation: 28,
          vocabulary: 34,
          grammar: 32,
          fluency: 31,
        },
      },
      {
        id: "s46",
        firstName: "Luca",
        lastName: "Colombo",
        email: "luca.colombo@example.com",
        photo: "https://i.pravatar.cc/150?img=50",
        level: "A1",
        progress: 22,
        activitiesCompleted: 3,
        activitiesTotal: 20,
        studyTimeMinutes: 50,
        score: 27,
        enrolledAt: oneWeekAgo.toISOString(),
        skills: {
          pronunciation: 20,
          vocabulary: 26,
          grammar: 24,
          fluency: 23,
        },
      },
      {
        id: "s47",
        firstName: "Sofia",
        lastName: "Ricci",
        email: "sofia.ricci@example.com",
        photo: "https://i.pravatar.cc/150?img=51",
        level: "A1",
        progress: 35,
        activitiesCompleted: 6,
        activitiesTotal: 20,
        studyTimeMinutes: 100,
        score: 42,
        enrolledAt: twoWeeksAgo.toISOString(),
        skills: {
          pronunciation: 33,
          vocabulary: 39,
          grammar: 37,
          fluency: 36,
        },
      },
      {
        id: "s48",
        firstName: "Matteo",
        lastName: "Marino",
        email: "matteo.marino@example.com",
        photo: "https://i.pravatar.cc/150?img=52",
        level: "A1",
        progress: 20,
        activitiesCompleted: 3,
        activitiesTotal: 20,
        studyTimeMinutes: 45,
        score: 25,
        enrolledAt: oneWeekAgo.toISOString(),
        skills: {
          pronunciation: 18,
          vocabulary: 24,
          grammar: 22,
          fluency: 21,
        },
      },
      {
        id: "s49",
        firstName: "Chiara",
        lastName: "Greco",
        email: "chiara.greco@example.com",
        photo: "https://i.pravatar.cc/150?img=53",
        level: "A1",
        progress: 27,
        activitiesCompleted: 4,
        activitiesTotal: 20,
        studyTimeMinutes: 70,
        score: 33,
        enrolledAt: oneWeekAgo.toISOString(),
        skills: {
          pronunciation: 25,
          vocabulary: 31,
          grammar: 29,
          fluency: 28,
        },
      },
      {
        id: "s50",
        firstName: "Andrea",
        lastName: "Bruno",
        email: "andrea.bruno@example.com",
        photo: "https://i.pravatar.cc/150?img=54",
        level: "A1",
        progress: 33,
        activitiesCompleted: 6,
        activitiesTotal: 20,
        studyTimeMinutes: 95,
        score: 40,
        enrolledAt: twoWeeksAgo.toISOString(),
        skills: {
          pronunciation: 31,
          vocabulary: 37,
          grammar: 35,
          fluency: 34,
        },
      },
      {
        id: "s51",
        firstName: "Elena",
        lastName: "Costa",
        email: "elena.costa@example.com",
        photo: "https://i.pravatar.cc/150?img=55",
        level: "A1",
        progress: 24,
        activitiesCompleted: 4,
        activitiesTotal: 20,
        studyTimeMinutes: 55,
        score: 29,
        enrolledAt: oneWeekAgo.toISOString(),
        skills: {
          pronunciation: 22,
          vocabulary: 28,
          grammar: 26,
          fluency: 25,
        },
      },
      {
        id: "s52",
        firstName: "Davide",
        lastName: "Fontana",
        email: "davide.fontana@example.com",
        photo: "https://i.pravatar.cc/150?img=56",
        level: "A1",
        progress: 29,
        activitiesCompleted: 5,
        activitiesTotal: 20,
        studyTimeMinutes: 80,
        score: 35,
        enrolledAt: twoWeeksAgo.toISOString(),
        skills: {
          pronunciation: 27,
          vocabulary: 33,
          grammar: 31,
          fluency: 30,
        },
      },
      {
        id: "s53",
        firstName: "Valentina",
        lastName: "Caruso",
        email: "valentina.caruso@example.com",
        photo: "https://i.pravatar.cc/150?img=57",
        level: "A1",
        progress: 26,
        activitiesCompleted: 4,
        activitiesTotal: 20,
        studyTimeMinutes: 65,
        score: 32,
        enrolledAt: oneWeekAgo.toISOString(),
        skills: {
          pronunciation: 24,
          vocabulary: 30,
          grammar: 28,
          fluency: 27,
        },
      },
      {
        id: "s54",
        firstName: "Simone",
        lastName: "Mancini",
        email: "simone.mancini@example.com",
        photo: "https://i.pravatar.cc/150?img=58",
        level: "A1",
        progress: 31,
        activitiesCompleted: 6,
        activitiesTotal: 20,
        studyTimeMinutes: 88,
        score: 37,
        enrolledAt: twoWeeksAgo.toISOString(),
        skills: {
          pronunciation: 29,
          vocabulary: 35,
          grammar: 33,
          fluency: 32,
        },
      },
      {
        id: "s55",
        firstName: "Giorgia",
        lastName: "Rizzo",
        email: "giorgia.rizzo@example.com",
        photo: "https://i.pravatar.cc/150?img=59",
        level: "A1",
        progress: 23,
        activitiesCompleted: 3,
        activitiesTotal: 20,
        studyTimeMinutes: 52,
        score: 28,
        enrolledAt: oneWeekAgo.toISOString(),
        skills: {
          pronunciation: 21,
          vocabulary: 27,
          grammar: 25,
          fluency: 24,
        },
      },
      {
        id: "s56",
        firstName: "Federico",
        lastName: "Moretti",
        email: "federico.moretti@example.com",
        photo: "https://i.pravatar.cc/150?img=60",
        level: "A1",
        progress: 34,
        activitiesCompleted: 6,
        activitiesTotal: 20,
        studyTimeMinutes: 105,
        score: 41,
        enrolledAt: twoWeeksAgo.toISOString(),
        skills: {
          pronunciation: 32,
          vocabulary: 38,
          grammar: 36,
          fluency: 35,
        },
      },
      {
        id: "s57",
        firstName: "Alessia",
        lastName: "Gallo",
        email: "alessia.gallo@example.com",
        photo: "https://i.pravatar.cc/150?img=61",
        level: "A1",
        progress: 21,
        activitiesCompleted: 3,
        activitiesTotal: 20,
        studyTimeMinutes: 48,
        score: 26,
        enrolledAt: oneWeekAgo.toISOString(),
        skills: {
          pronunciation: 19,
          vocabulary: 25,
          grammar: 23,
          fluency: 22,
        },
      },
    ];
  }

  // Class 7: Portuguese Conversation - 3 students, low progress
  if (classId === "7") {
    return [
      {
        id: "s58",
        firstName: "João",
        lastName: "Silva",
        email: "joao.silva@example.com",
        photo: "https://i.pravatar.cc/150?img=62",
        level: "A2",
        progress: 18,
        activitiesCompleted: 3,
        activitiesTotal: 20,
        studyTimeMinutes: 55,
        score: 22,
        enrolledAt: oneWeekAgo.toISOString(),
        skills: {
          pronunciation: 16,
          vocabulary: 22,
          grammar: 20,
          fluency: 19,
        },
      },
      {
        id: "s59",
        firstName: "Maria",
        lastName: "Santos",
        email: "maria.santos@example.com",
        photo: "https://i.pravatar.cc/150?img=63",
        level: "A2",
        progress: 15,
        activitiesCompleted: 2,
        activitiesTotal: 20,
        studyTimeMinutes: 40,
        score: 19,
        enrolledAt: oneWeekAgo.toISOString(),
        skills: {
          pronunciation: 13,
          vocabulary: 19,
          grammar: 17,
          fluency: 16,
        },
      },
      {
        id: "s60",
        firstName: "Pedro",
        lastName: "Oliveira",
        email: "pedro.oliveira@example.com",
        photo: "https://i.pravatar.cc/150?img=64",
        level: "A2",
        progress: 20,
        activitiesCompleted: 3,
        activitiesTotal: 20,
        studyTimeMinutes: 60,
        score: 24,
        enrolledAt: oneWeekAgo.toISOString(),
        skills: {
          pronunciation: 18,
          vocabulary: 24,
          grammar: 22,
          fluency: 21,
        },
      },
    ];
  }

  // Class 8: Spanish Literature - 4 students, very high progress
  if (classId === "8") {
    return [
      {
        id: "s61",
        firstName: "Diego",
        lastName: "Vargas",
        email: "diego.vargas@example.com",
        photo: "https://i.pravatar.cc/150?img=65",
        level: "C2",
        progress: 99,
        activitiesCompleted: 19,
        activitiesTotal: 20,
        studyTimeMinutes: 520,
        score: 98,
        enrolledAt: oneMonthAgo.toISOString(),
        skills: {
          pronunciation: 97,
          vocabulary: 99,
          grammar: 99,
          fluency: 98,
        },
      },
      {
        id: "s62",
        firstName: "Isabella",
        lastName: "Morales",
        email: "isabella.morales@example.com",
        photo: "https://i.pravatar.cc/150?img=66",
        level: "C2",
        progress: 97,
        activitiesCompleted: 18,
        activitiesTotal: 20,
        studyTimeMinutes: 500,
        score: 96,
        enrolledAt: oneMonthAgo.toISOString(),
        skills: {
          pronunciation: 95,
          vocabulary: 98,
          grammar: 97,
          fluency: 96,
        },
      },
      {
        id: "s63",
        firstName: "Santiago",
        lastName: "Herrera",
        email: "santiago.herrera@example.com",
        photo: "https://i.pravatar.cc/150?img=67",
        level: "C2",
        progress: 96,
        activitiesCompleted: 18,
        activitiesTotal: 20,
        studyTimeMinutes: 490,
        score: 95,
        enrolledAt: oneMonthAgo.toISOString(),
        skills: {
          pronunciation: 94,
          vocabulary: 97,
          grammar: 96,
          fluency: 95,
        },
      },
      {
        id: "s64",
        firstName: "Valeria",
        lastName: "Jimenez",
        email: "valeria.jimenez@example.com",
        photo: "https://i.pravatar.cc/150?img=68",
        level: "C2",
        progress: 98,
        activitiesCompleted: 19,
        activitiesTotal: 20,
        studyTimeMinutes: 510,
        score: 97,
        enrolledAt: oneMonthAgo.toISOString(),
        skills: {
          pronunciation: 96,
          vocabulary: 99,
          grammar: 98,
          fluency: 97,
        },
      },
    ];
  }

  // Class 10: English Pronunciation - 7 students, medium progress
  if (classId === "10") {
    return [
      {
        id: "s65",
        firstName: "Yuki",
        lastName: "Tanaka",
        email: "yuki.tanaka@example.com",
        photo: "https://i.pravatar.cc/150?img=69",
        level: "B1",
        progress: 65,
        activitiesCompleted: 12,
        activitiesTotal: 20,
        studyTimeMinutes: 240,
        score: 70,
        enrolledAt: twoWeeksAgo.toISOString(),
        skills: {
          pronunciation: 63,
          vocabulary: 72,
          grammar: 68,
          fluency: 66,
        },
      },
      {
        id: "s66",
        firstName: "Chen",
        lastName: "Wei",
        email: "chen.wei@example.com",
        photo: "https://i.pravatar.cc/150?img=70",
        level: "B1",
        progress: 58,
        activitiesCompleted: 11,
        activitiesTotal: 20,
        studyTimeMinutes: 210,
        score: 63,
        enrolledAt: twoWeeksAgo.toISOString(),
        skills: {
          pronunciation: 56,
          vocabulary: 65,
          grammar: 61,
          fluency: 59,
        },
      },
      {
        id: "s67",
        firstName: "Raj",
        lastName: "Patel",
        email: "raj.patel@example.com",
        photo: "https://i.pravatar.cc/150?img=71",
        level: "B1",
        progress: 62,
        activitiesCompleted: 12,
        activitiesTotal: 20,
        studyTimeMinutes: 230,
        score: 68,
        enrolledAt: twoWeeksAgo.toISOString(),
        skills: {
          pronunciation: 60,
          vocabulary: 69,
          grammar: 65,
          fluency: 63,
        },
      },
      {
        id: "s68",
        firstName: "Fatima",
        lastName: "Al-Rashid",
        email: "fatima.alrashid@example.com",
        photo: "https://i.pravatar.cc/150?img=72",
        level: "B1",
        progress: 55,
        activitiesCompleted: 10,
        activitiesTotal: 20,
        studyTimeMinutes: 190,
        score: 60,
        enrolledAt: oneWeekAgo.toISOString(),
        skills: {
          pronunciation: 53,
          vocabulary: 62,
          grammar: 58,
          fluency: 56,
        },
      },
      {
        id: "s69",
        firstName: "Alejandro",
        lastName: "Gonzalez",
        email: "alejandro.gonzalez@example.com",
        photo: "https://i.pravatar.cc/150?img=73",
        level: "B1",
        progress: 68,
        activitiesCompleted: 13,
        activitiesTotal: 20,
        studyTimeMinutes: 260,
        score: 73,
        enrolledAt: twoWeeksAgo.toISOString(),
        skills: {
          pronunciation: 66,
          vocabulary: 75,
          grammar: 71,
          fluency: 69,
        },
      },
      {
        id: "s70",
        firstName: "Mei",
        lastName: "Li",
        email: "mei.li@example.com",
        photo: "https://i.pravatar.cc/150?img=74",
        level: "B1",
        progress: 60,
        activitiesCompleted: 11,
        activitiesTotal: 20,
        studyTimeMinutes: 220,
        score: 65,
        enrolledAt: twoWeeksAgo.toISOString(),
        skills: {
          pronunciation: 58,
          vocabulary: 67,
          grammar: 63,
          fluency: 61,
        },
      },
      {
        id: "s71",
        firstName: "Hassan",
        lastName: "Ibrahim",
        email: "hassan.ibrahim@example.com",
        photo: "https://i.pravatar.cc/150?img=75",
        level: "B1",
        progress: 52,
        activitiesCompleted: 9,
        activitiesTotal: 20,
        studyTimeMinutes: 170,
        score: 57,
        enrolledAt: oneWeekAgo.toISOString(),
        skills: {
          pronunciation: 50,
          vocabulary: 59,
          grammar: 55,
          fluency: 53,
        },
      },
    ];
  }

  // Classes 6 and 9: No students (empty classes)
  return [];
}

/**
 * Composable for managing class students
 */
export const useClassStudents = () => {
  const students = ref<Student[]>([]);
  const loading = ref(false);
  const error = ref<string | null>(null);

  const fetchClassStudents = (classId: string) => {
    loading.value = true;
    error.value = null;

    try {
      // Load class from localStorage
      const storedClasses = loadClassesFromStorage();
      const classItem = storedClasses?.find((c) => c.id === classId);

      if (classItem && classItem.studentIds && classItem.studentIds.length > 0) {
        // Load students based on stored studentIds
        const allMockStudents = getMockClassStudents(classId);
        // Create a map for quick lookup
        const studentMap = new Map(allMockStudents.map((s) => [s.id, s]));
        // Filter students based on stored IDs
        students.value = classItem.studentIds
          .map((id) => studentMap.get(id))
          .filter((s): s is Student => s !== undefined);
      } else {
        // No stored studentIds, use mock data and save it
        const mockStudents = getMockClassStudents(classId);
        students.value = mockStudents;

        // Save studentIds to class in localStorage
        if (classItem) {
          const studentIds = mockStudents.map((s) => s.id);
          const updatedClass = {
            ...classItem,
            studentIds,
            students: studentIds.length,
            updatedAt: new Date().toISOString(),
          };

          const updatedClasses = storedClasses ? storedClasses.map((c) => (c.id === classId ? updatedClass : c)) : [];
          saveClassesToStorage(updatedClasses);
        }
      }
    } catch (err) {
      error.value = err instanceof Error ? err.message : "Error fetching class students";
      // Fallback to mock data on error
      students.value = getMockClassStudents(classId);
    } finally {
      loading.value = false;
    }
  };

  const addStudent = (classId: string, studentId: string) => {
    try {
      const storedClasses = loadClassesFromStorage();
      const classItem = storedClasses?.find((c) => c.id === classId);

      if (classItem) {
        const currentStudentIds = classItem.studentIds || [];
        if (!currentStudentIds.includes(studentId)) {
          // Add student ID
          const updatedStudentIds = [...currentStudentIds, studentId];
          const updatedClass = {
            ...classItem,
            studentIds: updatedStudentIds,
            students: updatedStudentIds.length,
            updatedAt: new Date().toISOString(),
          };

          // Update in storage
          if (storedClasses) {
            const updatedClasses = storedClasses.map((c) => (c.id === classId ? updatedClass : c));
            saveClassesToStorage(updatedClasses);
          }

          // Update local students list
          const allMockStudents = getMockClassStudents(classId);
          const student = allMockStudents.find((s) => s.id === studentId);
          if (student) {
            students.value = [...students.value, student];
          }
        }
      }
    } catch (err) {
      // Error handling: silently fail or implement proper error notification
      console.error("Error adding student to class:", err);
    }
  };

  const removeStudent = (classId: string, studentId: string) => {
    try {
      const storedClasses = loadClassesFromStorage();
      const classItem = storedClasses?.find((c) => c.id === classId);

      if (classItem) {
        const currentStudentIds = classItem.studentIds || [];
        const updatedStudentIds = currentStudentIds.filter((id) => id !== studentId);
        const updatedClass = {
          ...classItem,
          studentIds: updatedStudentIds,
          students: updatedStudentIds.length,
          updatedAt: new Date().toISOString(),
        };

        // Update in storage
        if (storedClasses) {
          const updatedClasses = storedClasses.map((c) => (c.id === classId ? updatedClass : c));
          saveClassesToStorage(updatedClasses);
        }

        // Update local students list
        students.value = students.value.filter((s) => s.id !== studentId);
      }
    } catch (err) {
      // Error handling: silently fail or implement proper error notification
      console.error("Error removing student from class:", err);
    }
  };

  return {
    students,
    loading,
    error,
    fetchClassStudents,
    addStudent,
    removeStudent,
  };
};
