# Generated by Django 5.2.8 on 2025-12-09 17:40

import core.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import django_currentuser.db.models.fields
import django_currentuser.middleware
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="User ID",
                    ),
                ),
                (
                    "onboarding_completed",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates whether the user has completed the onboarding process",
                        verbose_name="Onboarding Completed",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "user",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Classroom",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        blank=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "public_id",
                    core.models.DynamicPrefixShortUUIDField(
                        alphabet=None,
                        blank=True,
                        editable=False,
                        length=16,
                        max_length=40,
                        prefix="",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date when this record was created.",
                        null=True,
                        verbose_name="Creation Date",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date when this record was last modified.",
                        null=True,
                        verbose_name="Last Updated",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True,
                        default=True,
                        help_text="Indicates whether this record is active in the platform.",
                        verbose_name="Active",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "unique_code",
                    models.CharField(
                        help_text="8-character uppercase alphanumeric code for auto-enrollment (e.g., 'ABC12345')",
                        max_length=8,
                        unique=True,
                        verbose_name="Unique Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Subject"
                    ),
                ),
                (
                    "grade_level",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Grade Level"
                    ),
                ),
                (
                    "settings",
                    models.JSONField(blank=True, default=dict, verbose_name="Settings"),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        blank=True,
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        help_text="User who created this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "deleted_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        blank=True,
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Deleted By",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        help_text="User who last modified this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        on_update=True,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "db_table": "classroom",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        blank=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "public_id",
                    core.models.DynamicPrefixShortUUIDField(
                        alphabet=None,
                        blank=True,
                        editable=False,
                        length=16,
                        max_length=40,
                        prefix="",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date when this record was created.",
                        null=True,
                        verbose_name="Creation Date",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date when this record was last modified.",
                        null=True,
                        verbose_name="Last Updated",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True,
                        default=True,
                        help_text="Indicates whether this record is active in the platform.",
                        verbose_name="Active",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="Slug"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "logo",
                    models.TextField(blank=True, null=True, verbose_name="Logo URL"),
                ),
                (
                    "website",
                    models.URLField(blank=True, null=True, verbose_name="Website"),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Contact Email",
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Contact Phone",
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Address"),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="City"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        help_text="ISO 3166-1 alpha-2 country code",
                        max_length=2,
                        null=True,
                        verbose_name="Country",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="UTC", max_length=50, verbose_name="Timezone"
                    ),
                ),
                (
                    "settings",
                    models.JSONField(blank=True, default=dict, verbose_name="Settings"),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        blank=True,
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        help_text="User who created this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "deleted_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        blank=True,
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Deleted By",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        help_text="User who last modified this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        on_update=True,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "db_table": "institution",
            },
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        blank=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "public_id",
                    core.models.DynamicPrefixShortUUIDField(
                        alphabet=None,
                        blank=True,
                        editable=False,
                        length=16,
                        max_length=40,
                        prefix="",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date when this record was created.",
                        null=True,
                        verbose_name="Creation Date",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date when this record was last modified.",
                        null=True,
                        verbose_name="Last Updated",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True,
                        default=True,
                        help_text="Indicates whether this record is active in the platform.",
                        verbose_name="Active",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin_institucional", "Institutional Admin"),
                            ("coordinator", "Coordinator"),
                            ("admin_sede", "Sede Admin"),
                            ("teacher", "Teacher"),
                            ("student", "Student"),
                            ("viewer", "Viewer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("token", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("revoked", "Revoked"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "accepted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "declined_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("welcome_message", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        blank=True,
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        help_text="User who created this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "deleted_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        blank=True,
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Deleted By",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revoked_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        help_text="User who last modified this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        on_update=True,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "db_table": "invitation",
            },
        ),
        migrations.CreateModel(
            name="InvitationClassroom",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitation_classrooms",
                        to="authentication.classroom",
                        verbose_name="Classroom",
                    ),
                ),
                (
                    "invitation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitation_classrooms",
                        to="authentication.invitation",
                        verbose_name="Invitation",
                    ),
                ),
            ],
            options={
                "db_table": "invitation_classroom",
            },
        ),
        migrations.AddField(
            model_name="invitation",
            name="classrooms",
            field=models.ManyToManyField(
                blank=True,
                related_name="invitations",
                through="authentication.InvitationClassroom",
                to="authentication.classroom",
            ),
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        blank=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "public_id",
                    core.models.DynamicPrefixShortUUIDField(
                        alphabet=None,
                        blank=True,
                        editable=False,
                        length=16,
                        max_length=40,
                        prefix="",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date when this record was created.",
                        null=True,
                        verbose_name="Creation Date",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date when this record was last modified.",
                        null=True,
                        verbose_name="Last Updated",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True,
                        default=True,
                        help_text="Indicates whether this record is active in the platform.",
                        verbose_name="Active",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Language code (e.g., 'en', 'es', 'fr')",
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "native_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        blank=True,
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        help_text="User who created this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "deleted_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        blank=True,
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Deleted By",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        help_text="User who last modified this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        on_update=True,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "db_table": "language",
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="classroom",
            name="language",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="classrooms",
                to="authentication.language",
                verbose_name="Language",
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        blank=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "public_id",
                    core.models.DynamicPrefixShortUUIDField(
                        alphabet=None,
                        blank=True,
                        editable=False,
                        length=16,
                        max_length=40,
                        prefix="",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date when this record was created.",
                        null=True,
                        verbose_name="Creation Date",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date when this record was last modified.",
                        null=True,
                        verbose_name="Last Updated",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True,
                        default=True,
                        help_text="Indicates whether this record is active in the platform.",
                        verbose_name="Active",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "primary_role",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("teacher", "Teacher"),
                            ("admin_institucional", "Institutional Admin"),
                        ],
                        max_length=20,
                        verbose_name="Primary Role",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Phone"
                    ),
                ),
                (
                    "photo",
                    models.TextField(blank=True, null=True, verbose_name="Photo URL"),
                ),
                ("bio", models.TextField(blank=True, null=True, verbose_name="Bio")),
                (
                    "timezone",
                    models.CharField(
                        default="UTC", max_length=50, verbose_name="Timezone"
                    ),
                ),
                (
                    "language_preference",
                    models.CharField(
                        default="en", max_length=10, verbose_name="Language Preference"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=30, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=30, verbose_name="Last Name"),
                ),
                (
                    "birthday",
                    models.DateField(blank=True, null=True, verbose_name="Birthday"),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        help_text="ISO 3166-1 alpha-2 country code (2 uppercase letters)",
                        max_length=2,
                        null=True,
                        verbose_name="Country",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CC", "Cédula de Ciudadanía"),
                            ("CE", "Cédula de Extranjería"),
                            ("DNI", "Documento Nacional de Identidad"),
                            ("PAS", "Pasaporte"),
                            ("TI", "Tarjeta de Identidad"),
                            ("OTHER", "Otro"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Document Type",
                    ),
                ),
                (
                    "document_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Document Number",
                    ),
                ),
                (
                    "document_type_other",
                    models.TextField(
                        blank=True,
                        help_text="Only used if document_type is OTHER",
                        null=True,
                        verbose_name="Document Type Other",
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        blank=True,
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        help_text="User who created this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "deleted_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        blank=True,
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Deleted By",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        help_text="User who last modified this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        on_update=True,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "db_table": "user_profile",
            },
        ),
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        blank=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "public_id",
                    core.models.DynamicPrefixShortUUIDField(
                        alphabet=None,
                        blank=True,
                        editable=False,
                        length=16,
                        max_length=40,
                        prefix="",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date when this record was created.",
                        null=True,
                        verbose_name="Creation Date",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date when this record was last modified.",
                        null=True,
                        verbose_name="Last Updated",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True,
                        default=True,
                        help_text="Indicates whether this record is active in the platform.",
                        verbose_name="Active",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("personal", "Personal"),
                            ("institution_sede", "Institution Sede"),
                            ("shared", "Shared"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="Slug"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "settings",
                    models.JSONField(blank=True, default=dict, verbose_name="Settings"),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        blank=True,
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        help_text="User who created this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "deleted_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        blank=True,
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Deleted By",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspaces",
                        to="authentication.institution",
                        verbose_name="Institution",
                    ),
                ),
                (
                    "owner_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_workspaces",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner User",
                    ),
                ),
                (
                    "parent_workspace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_workspaces",
                        to="authentication.workspace",
                        verbose_name="Parent Workspace",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        help_text="User who last modified this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        on_update=True,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "db_table": "workspace",
            },
        ),
        migrations.CreateModel(
            name="UserWorkspaceMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        blank=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "public_id",
                    core.models.DynamicPrefixShortUUIDField(
                        alphabet=None,
                        blank=True,
                        editable=False,
                        length=16,
                        max_length=40,
                        prefix="",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date when this record was created.",
                        null=True,
                        verbose_name="Creation Date",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date when this record was last modified.",
                        null=True,
                        verbose_name="Last Updated",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True,
                        default=True,
                        help_text="Indicates whether this record is active in the platform.",
                        verbose_name="Active",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin_institucional", "Institutional Admin"),
                            ("coordinator", "Coordinator"),
                            ("admin_sede", "Sede Admin"),
                            ("teacher", "Teacher"),
                            ("student", "Student"),
                            ("viewer", "Viewer"),
                        ],
                        max_length=20,
                        verbose_name="Role",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("invited", "Invited"),
                            ("suspended", "Suspended"),
                            ("left", "Left"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Joined At"
                    ),
                ),
                (
                    "left_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Left At"),
                ),
                (
                    "permissions",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Permissions"
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        blank=True,
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        help_text="User who created this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "deleted_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        blank=True,
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Deleted By",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workspace_membership_invitations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Invited By",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        help_text="User who last modified this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        on_update=True,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="authentication.workspace",
                        verbose_name="Workspace",
                    ),
                ),
            ],
            options={
                "db_table": "user_workspace_membership",
            },
        ),
        migrations.AddField(
            model_name="invitation",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitations",
                to="authentication.workspace",
            ),
        ),
        migrations.AddField(
            model_name="classroom",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classrooms",
                to="authentication.workspace",
                verbose_name="Workspace",
            ),
        ),
        migrations.CreateModel(
            name="ClassroomMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        blank=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "public_id",
                    core.models.DynamicPrefixShortUUIDField(
                        alphabet=None,
                        blank=True,
                        editable=False,
                        length=16,
                        max_length=40,
                        prefix="",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date when this record was created.",
                        null=True,
                        verbose_name="Creation Date",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date when this record was last modified.",
                        null=True,
                        verbose_name="Last Updated",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True,
                        default=True,
                        help_text="Indicates whether this record is active in the platform.",
                        verbose_name="Active",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("teacher", "Teacher"),
                            ("assistant", "Assistant"),
                        ],
                        default="student",
                        max_length=20,
                        verbose_name="Role",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Joined At"
                    ),
                ),
                (
                    "left_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the user left the classroom (NULL if still active)",
                        null=True,
                        verbose_name="Left At",
                    ),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="authentication.classroom",
                        verbose_name="Classroom",
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        blank=True,
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        help_text="User who created this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "deleted_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        blank=True,
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Deleted By",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        help_text="User who last modified this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        on_update=True,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classroom_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "db_table": "classroom_membership",
                "indexes": [
                    models.Index(
                        condition=models.Q(("is_active", True)),
                        fields=["classroom", "user"],
                        name="idx_classroom_memb_active",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("classroom", "user"), name="uniq_classroom_user"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="invitationclassroom",
            index=models.Index(fields=["invitation"], name="idx_inv_classroom_inv"),
        ),
        migrations.AddIndex(
            model_name="invitationclassroom",
            index=models.Index(fields=["classroom"], name="idx_inv_classroom_class"),
        ),
        migrations.AddConstraint(
            model_name="invitationclassroom",
            constraint=models.UniqueConstraint(
                fields=("invitation", "classroom"), name="uniq_invitation_classroom"
            ),
        ),
        migrations.AddIndex(
            model_name="language",
            index=models.Index(fields=["code"], name="idx_languages_code"),
        ),
        migrations.AddIndex(
            model_name="language",
            index=models.Index(
                condition=models.Q(("is_active", True)),
                fields=["is_active"],
                name="idx_languages_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="userprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("country__regex", "^[A-Z]{2}$"),
                    ("country__isnull", True),
                    _connector="OR",
                ),
                name="chk_user_profile_country_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="workspace",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("institution__isnull", True),
                        ("owner_user__isnull", False),
                        ("type", "personal"),
                    ),
                    models.Q(
                        ("institution__isnull", False), ("type", "institution_sede")
                    ),
                    ("type", "shared"),
                    _connector="OR",
                ),
                name="chk_workspace_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="userworkspacemembership",
            constraint=models.UniqueConstraint(
                fields=("user", "workspace", "role"), name="uniq_user_workspace_role"
            ),
        ),
        migrations.AddConstraint(
            model_name="invitation",
            constraint=models.CheckConstraint(
                condition=models.Q(("expires_at__gt", models.F("created_at"))),
                name="chk_invitation_expiry",
            ),
        ),
    ]
